
"""practice_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMwEZqmsGn4sHioAme87MmJrEl54Me_Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_val_score,StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

data=pd.read_csv('heart.csv')
df=pd.DataFrame(data)
df=df.drop_duplicates()
df["age"] = pd.to_numeric(df["age"])
x=df.drop("target",axis=1)
y=df["target"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
model=LogisticRegression(C=0.1,max_iter=5000)
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)
accuracy=accuracy_score(y_test,y_pred)
cv=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
scores=cross_val_score(
    model,
    x_train_scaled,
    y_train,
    cv=cv,
    scoring='accuracy'
)
plt.figure(figsize=(14,12))
sns.heatmap(
    df.corr(),
    annot=True
)
plt.show()

x=df.drop(["restecg","fbs","chol","target"],axis=1)
y=df["target"]
cv=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
scores=cross_val_score(
    model,
    x_train_scaled,
    y_train,
    cv=cv,
    scoring='accuracy'
)
print(scores.mean())

cv=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
scores=cross_val_score(
    model,
    x_train_scaled,
    y_train,
    cv=cv,
    scoring='f1'
)
print(scores.mean())

from sklearn.model_selection import GridSearchCV
params = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100]
}
grid=GridSearchCV(
    model,
    params,
    cv=cv,
    scoring='accuracy'
)
grid.fit(x_train_scaled,y_train)
print(grid.best_params_)
print(grid.best_score_)

cv=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
model1=SVC()
params = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", "auto", 0.01, 0.1, 1],
    "kernel": ["linear", "rbf"]
}
scores=cross_val_score(
    model1,
    x_train_scaled,
    y_train,
    cv=cv,
    scoring='accuracy'
)
grid=GridSearchCV(
    model1,
    params,
    cv=cv,
    scoring='accuracy'
)
grid.fit(x_train_scaled,y_train)
print(f"Best Params: {grid.best_params_}")
print(f"Best Score: {grid.best_score_}")

x=df.drop(["restecg","fbs","chol","target"],axis=1)
y=df["target"]
cv=StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
scores=cross_val_score(
    model,
    x_train_scaled,
    y_train,
    cv=cv,
    scoring='accuracy'
)
from sklearn.model_selection import GridSearchCV
params = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100]
}
grid=GridSearchCV(
    model,
    params,
    cv=cv,
    scoring='accuracy'
)
grid.fit(x_train_scaled,y_train)
print(grid.best_params_)
print(grid.best_score_)
best_model=grid.best_estimator_
y_pred=best_model.predict(x_test_scaled)
accuracy=accuracy_score(y_pred,y_test)
print(accuracy)

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

model_params = {
    "Logistic Regression": (
        LogisticRegression(max_iter=5000),
        {
            "C": [0.001, 0.01, 0.1, 1, 10, 100]
        }
    ),
    "SVC": (
        SVC(),
        {
            "C": [0.1, 1, 10, 100],
            "kernel": ["linear", "rbf"],
            "gamma": ["scale", "auto"]
        }
    ),
    "KNN": (
        KNeighborsClassifier(),
        {
            "n_neighbors": [3, 5, 7, 9, 11],
            "weights": ["uniform", "distance"],
            "metric": ["euclidean", "manhattan"]
        }
    ),
    "Random Forest": (
        RandomForestClassifier(random_state=42),
        {
            "n_estimators": [100, 200, 300],
            "max_depth": [None, 5, 10, 20],
            "min_samples_split": [2, 5, 10]
        }
    ),
    "Gradient Boosting": (
        GradientBoostingClassifier(random_state=42),
        {
            "n_estimators": [100, 200],
            "learning_rate": [0.01, 0.1, 0.2],
            "max_depth": [2, 3, 5]
        }
    )
}

results = []
for name, (estimator, params) in model_params.items():
    grid = GridSearchCV(
        estimator,
        params,
        cv=cv,
        scoring='f1',
        n_jobs=-1
    )
    grid.fit(x_train_scaled, y_train)
    results.append({
        "Model": name,
        "Best Params": grid.best_params_,
        "Best Score": grid.best_score_
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    "Best Score",
    ascending=False
)
print(results_df)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))

sns.boxplot(data=x)
plt.xticks(rotation=90)
plt.show()

Q1 = x.quantile(0.25)
Q3 = x.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = ((x < lower) | (x > upper))

print(outliers.sum())

for col in ['trestbps', 'thalach', 'oldpeak']:
    Q1 = x[col].quantile(0.25)
    Q3 = x[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    print("\n", col)
    print(x[(x[col] < lower) | (x[col] > upper)][col])

import pickle
with open("heart_model.pkl","wb") as file:
  pickle.dump(model,file)

with open("scaler.pkl","wb") as file:
  pickle.dump(scaler,file)

import streamlit as st
import pandas as pd
import pickle
with open("heart_model.pkl", "rb") as file:
    model = pickle.load(file)
with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

st.title("Heart Disease Prediction")
st.write("Enter the patient's information below.")

age = st.number_input("Age", min_value=1, max_value=120, value=50)

sex_option = st.selectbox("Sex", ["Female", "Male"])
sex = 0 if sex_option == "Female" else 1

cp_option = st.selectbox(
    "Chest Pain Type",
    [
        "Typical Angina",
        "Atypical Angina",
        "Non-anginal Pain",
        "Asymptomatic"
    ]
)

cp_mapping = {
    "Typical Angina": 0,
    "Atypical Angina": 1,
    "Non-anginal Pain": 2,
    "Asymptomatic": 3
}

cp = cp_mapping[cp_option]

trestbps = st.number_input(
    "Resting Blood Pressure",
    min_value=50,
    max_value=250,
    value=120
)

thalach = st.number_input(
    "Maximum Heart Rate",
    min_value=50,
    max_value=250,
    value=150
)

exang_option = st.selectbox(
    "Exercise Induced Angina",
    ["No", "Yes"]
)

exang = 0 if exang_option == "No" else 1

oldpeak = st.number_input(
    "Oldpeak",
    min_value=0.0,
    max_value=10.0,
    value=1.0
)

slope_option = st.selectbox(
    "Slope",
    ["Upsloping", "Flat", "Downsloping"]
)

slope_mapping = {
    "Upsloping": 0,
    "Flat": 1,
    "Downsloping": 2
}
slope = slope_mapping[slope_option]
ca = st.selectbox(
    "Number of Major Vessels",
    [0, 1, 2, 3, 4]
)
thal_option = st.selectbox(
    "Thalassemia",
    ["Normal", "Fixed Defect", "Reversible Defect"]
)

thal_mapping = {
    "Normal": 1,
    "Fixed Defect": 2,
    "Reversible Defect": 3
}

thal = thal_mapping[thal_option]

if st.button("Predict"):
    new_data = pd.DataFrame({
        "age": [age],
        "sex": [sex],
        "cp": [cp],
        "trestbps": [trestbps],
        "thalach": [thalach],
        "exang": [exang],
        "oldpeak": [oldpeak],
        "slope": [slope],
        "ca": [ca],
        "thal": [thal]
    })
    new_data_scaled = scaler.transform(new_data)
    prediction = model.predict(new_data_scaled)
    if prediction[0]==0:
      st.write("You does not have a heart disease!")
    else:
      st.write("You have a heart disease! You should go see a doctor!")

